server:
  port: 9998
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qinggong?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Gzbd2020
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 6000
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    # Redis最大连接数
    maxTotal: 100
    # Redis最大最小空闲连接数
    maxIdle: 50
    minIdle: 20
    timeout: 3000
  #配置资源访问路径
  mvc:
    static-path-pattern: /**
  #配置资源映射路径
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
mybatis:
  mapper-locations: classpath:mapping/*.xml,classpath:mapping/*/*.xml
logging:
  level:
    com.manage.qinggong:
      debug
user:
  prop: D:/user.txt
#verify:
#  url:
##    http://localhost:9999/order/decodeQR?orderUserName=%s&orderDateStr=%s&orderTime=%s
#    http://192.168.0.182:9999/order/decodeQR?orderUserName=%s&orderDateStr=%s&orderTime=%s
web:
  upload-path: D:/ppp/